export default {
  school: {
    SAS: "School of Arts & Sciences",
    MS: "Military Science",
    SC: "School of Communication & Info (U)",
    SEd: "Graduate School of Education (U)",
    MGSA: "Mason Gross School of the Arts (U)",
    SSW: "School of Social Work (U)",
    BSP: "Bloustein School of Planning (U)",
    SEBS: "School of Environmental & Biological Sci",
    SAPP: "Grad School of Applied & Prof Psych (U)",
    SEn: "School of Engineering",
    EMAP: "Ernest Mario School of Pharmacy (U)",
    RBS: "Rutgers Business School- NB campus (U)",
    SMLR: "School of Management & Labor Rel (U)",
    SN: "School of Nursing - New Brunswick (U)",
  },
  schoolCode: {
    SAS: "01",
    MS: "03",
    SC: "04",
    SE: "05",
    MGSA: "07",
    SSW: "09",
    BSP: "10",
    SEBS: "11",
    SAPP: "13",
    SEn: "14",
    EMAP: "30",
    RBS: "33",
    SMLR: "37",
    SN: "77",
  },
  campus: {
    BU: "Busch",
    LI: "Livingston",
    CA: "College Avenue",
    CD: "C/D",
    DOWN: "Downtown New Brunswick",
    OFF: "Off Campus",
    ON: "Online",
    SA: "Study Abroad",
    NA: "N/A",
    ASYNC: -1
  },
  credit: {
    ONE: "1",
    TWO: "2",
    THREE: "3",
    FOUR: "4",
    CBA: "Credits by arrangement",
    NA: "N/A",
  },
  coreCode: {
    CE: "Non-Core: Community Engagement (CE)",
    AHo: "Philosophical and Theoretical Issues (AHo)",
    AHp: "Arts and Literatures (AHp)",
    AHq: "Nature of Languages (AHq)",
    AHr: "Critical Creative Expression (AHr)",
    CCD: "Diversities and Social Inequalities (CCD)",
    CCO: "Our Common Future (CCO)",
    HST: "Historical Analysis (HST)",
    NS: "Natural Sciences (NS)",
    QQ: "Quantitative Information (QQ)",
    QR: "Mathematical or Formal Reasoning (QR)",
    WC: "Writing and Communication 01:355:101 (WC)",
    WCr: "Writing and Communication, Revision (WCr)",
    WCd: "Writing and Communication in a Discipline (WCd)",
    ITR: "Information Technology and Research (ITR)",
    SCL: "Social Analysis (SCL)",
    ECN: "SEBS Only: Economic Analysis (ECN)",
    GVT: "SEBS Only: Government/Regulatory Analysis (GVT)",
    SOEHS: "SOE Only: Approved Humanities/Social Science (SOEHS)",
  },
  courseType: {
    FtF: "Face to Face",
    H: "Hybrid",
    O: "Online",
  },
};
